<?php declare(strict_types=1);

use Bruha\Tracy\SqlCheckerPanel;
use Bruha\Tracy\Query;

?>
<h1>SQL Checker: Logs contains <?=SqlCheckerPanel::number(count($queries))?> queries with <?=SqlCheckerPanel::number($duration, 1)?> ms duration</h1>
<style>
    div[id^='tracy-debug-panel-Bruha-Tracy-SqlCheckerPanel'] {
        width: 1250px !important;
        max-width: 1250px !important;
    }

    div[id^='tracy-debug-panel-Bruha-Tracy-SqlCheckerPanel'] h1 {
        width: 100% !important;;
        max-width: 1250px !important;
    }

    div[id^='tracy-debug-panel-Bruha-Tracy-SqlCheckerPanel'] tr th {
        text-align: center !important;
    }

    div[id^='tracy-debug-panel-Bruha-Tracy-SqlCheckerPanel'] tr th.fixed-width {
        min-width: 150px !important;
        width: 150px !important;
        max-width: 150px !important;
    }

    div[id^='tracy-debug-panel-Bruha-Tracy-SqlCheckerPanel'] tr th.fixed-width-450 {
        min-width: 450px !important;
        width: 450px !important;
        max-width: 450px !important;
    }

    div[id^='tracy-debug-panel-Bruha-Tracy-SqlCheckerPanel'] tr td {
        background-color: #FDF5CE !important;
        vertical-align: middle !important;
    }

    div[id^='tracy-debug-panel-Bruha-Tracy-SqlCheckerPanel'] tr td.link {
        cursor: pointer !important;
    }

    div[id^='tracy-debug-panel-Bruha-Tracy-SqlCheckerPanel'] tr td.center {
        text-align: center !important;
    }

    div[id^='tracy-debug-panel-Bruha-Tracy-SqlCheckerPanel'] tr td.fixed-width {
        min-width: 150px !important;
        width: 150px !important;
        max-width: 150px !important;
    }

    div[id^='tracy-debug-panel-Bruha-Tracy-SqlCheckerPanel'] tr td.fixed-width-450 {
        min-width: 140px !important;
        width: 450px !important;
        max-width: 450px !important;
    }

    div[id^='tracy-debug-panel-Bruha-Tracy-SqlCheckerPanel'] tr.separator td {
        background-color: #FFFFFF !important;
    }

    div[id^='tracy-debug-panel-Bruha-Tracy-SqlCheckerPanel'] tbody:last-child tr.separator:last-child {
        display: none;
    }
</style>
<script>
    for (const element of document.querySelectorAll('.open-close')) {
        element.style.display = 'none';
    }

    function openClose(selector) {
        for (const element of document.querySelectorAll(`.${selector}`)) {
            element.style.display = element.style.display === 'none' ? 'table-row-group' : 'none';
        }
    }
</script>
<div class='tracy-inner'>
    <table>
        <thead>
            <tr>
                <th class='fixed-width'>Duration / Table</th>
                <th class='fixed-width'>Query / Type</th>
                <th colspan='3'>Query / Indexes</th>
                <th class='fixed-width'>Query / Rows</th>
                <th class='fixed-width'>Explain / Backtrace / Extra</th>
            </tr>
        </thead>
<?php /** @var Query[] $queries */
foreach ($queries as $query): ?>
        <tbody>
            <tr>
                <td class='fixed-width center'><?=SqlCheckerPanel::number($query->getDuration(), 1)?> ms</td>
                <td colspan='5' class='center'><strong><?=$query->getParameterizedQuery()?></strong></td>
                <td class='fixed-width link center' onclick="openClose('hash-<?=md5($query->getQuery())?>');">Explain / Backtrace</td>
            </tr>
        </tbody>
        <tbody class='open-close hash-<?=md5($query->getQuery())?>'>
<?php foreach ($query->getExplain() as $explain): ?>
            <tr>
                <td class='fixed-width center'><?=$explain->getTable()?></td>
                <td class='fixed-width center'><?=$explain->getType()?></td>
                <td colspan='3' class='center' title='<?= implode('&#10;', $explain->getKeys())?>'><?=$explain->getKey() ?: '&mdash;'?></td>
                <td class='fixed-width center'><?=SqlCheckerPanel::number($explain->getRows())?> (<?=$explain->getFiltered()?>%)</td>
                <td class='fixed-width center'><?=$explain->getExtra()?></td>
            </tr>
<?php endforeach; ?>
        </tbody>
        <tbody class='open-close hash-<?=md5($query->getQuery())?>'>
<?php foreach ($query->getFormattedBacktraces() as $backtraces): ?>
            <tr>
                <td colspan='3' class='fixed-width-450 center'><?=$backtraces[0]?></td>
                <td class='fixed-width'></td>
                <td colspan='3' class='fixed-width-450 center'><?=$backtraces[1]?></td>
            </tr>
<?php endforeach; ?>
        </tbody>
        <tbody>
            <tr class='separator'>
                <td colspan='7' class='separator'>&nbsp;</td>
            </tr>
        </tbody>
<?php endforeach; ?>
    </table>
</div>
